
# Latent Brownian Bridge Diffusion Model Template(Latent Space)
training:
  n_epochs: 100
  n_steps: 200000
  save_interval: 5000
  val_interval: 1000

data:
  dataset_name: 'dataset_name'
  dataset_type: 'custom_aligned'
  dataset_config:
    dataset_path: 'dataset_path'
    image_size: 256
    channels: 3
    to_normal: True
    flip: True
  train:
    batch_size: 8
    shuffle: True
  val:
    batch_size: 8
    shuffle: True
  test:
    batch_size: 8
    # shuffle: False

model:
  model_name: "LBBDM-f16" # part of result path
  model_type: "LBBDM" # specify a module
  normalize_latent: False
  only_load_latent_mean_std: False
  # model_load_path:  # model checkpoint path
  # optim_sche_load_path:  # optimizer scheduler checkpoint path

  EMA:
    use_ema: True
    ema_decay: 0.995
    update_ema_interval: 8 # step
    start_ema_step: 30000

  BB:
    optimizer:
      weight_decay: 0.000
      optimizer: 'Adam'
      lr: 1.e-4
      beta1: 0.9

    lr_scheduler:
      factor: 0.5
      patience: 3000
      threshold: 0.0001
      cooldown: 3000
      min_lr: 5.e-7

    params:
      mt_type: 'linear' # options {'linear', 'sin'}
      objective: 'grad' # options {'grad', 'noise', 'ysubx'}
      loss_type: 'l1' # options {'l1', 'l2'}

      skip_sample: True
      sample_type: 'linear' # options {"linear", "sin"}
      sample_step: 200

      num_timesteps: 1000 # timesteps
      eta: 1.0 # DDIM reverse process eta
      max_var: 1.0 # maximum variance

      UNetParams:
        image_size: 16
        in_channels: 8
        model_channels: 128
        out_channels: 8
        num_res_blocks: 2
        attention_resolutions: !!python/tuple
          - 16
          - 8
          - 4
        channel_mult: !!python/tuple
          - 1
          - 4
          - 8
        conv_resample: True
        dims: 2
        num_heads: 8
        num_head_channels: 64
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: True
        condition_key: "VoxelNet" # options {"VoxelNet", "first_stage", "nocond"}
